version: '3.8'

networks:
  traefik:
    external: true

services:
  react-app:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.http.routers.website.rule=Host(`website.whitney.rip`)
      - traefik.http.routers.website.tls=true
      - traefik.http.routers.website.tls.certresolver=lets-encrypt
      - traefik.http.services.website.loadbalancer.server.port=80
      - traefik.port=80