networks:
  traefik:
    external: true

services:
  react-app:
    container_name: content-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.http.routers.content-website.rule=Host(`content.whitney.rip`)
      - traefik.http.routers.content-website.tls=true
      - traefik.http.routers.content-website.tls.certresolver=lets-encrypt
      - traefik.http.services.content-website.loadbalancer.server.port=80
      - traefik.port=80
